name: server

services:
  # server:
  #   env_file:
  #     - .env
  db:
    container_name: postgres
    image: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env
    expose:
      - "5432"
  redis:
    env_file:
    - .env
    container_name: redis
    restart: always
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"
